//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Lumos
{
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  public class Resource
  {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resource()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
      get
      {
        if (object.ReferenceEquals(resourceMan, null))
        {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PryazilimProject.Resource", typeof(Resource).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture
    {
      get
      {
        return resourceCulture;
      }
      set
      {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Anasayfa.
    /// </summary>
    public static string ANASAYFA
    {
      get
      {
        return ResourceManager.GetString("ANASAYFA", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lütfen reCapctha&apos;yı Doğrulayınız.
    /// </summary>
    public static string CapcthaMessage
    {
      get
      {
        return ResourceManager.GetString("CapcthaMessage", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to E-Posta Adresi.
    /// </summary>
    public static string EPosta
    {
      get
      {
        return ResourceManager.GetString("EPosta", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Ulaşmak istediğiniz sayfa bulunamadı. Anasayfaya dönmek için aşağıdaki butona tıklayabilirsiniz..
    /// </summary>
    public static string ErrorText
    {
      get
      {
        return ResourceManager.GetString("ErrorText", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Gönder.
    /// </summary>
    public static string Gonder
    {
      get
      {
        return ResourceManager.GetString("Gonder", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hakkımızda.
    /// </summary>
    public static string HAKKIMIZDA
    {
      get
      {
        return ResourceManager.GetString("HAKKIMIZDA", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to HIZLI MENÜ.
    /// </summary>
    public static string HizliMenu
    {
      get
      {
        return ResourceManager.GetString("HizliMenu", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Hizmetler.
    /// </summary>
    public static string Hizmetler
    {
      get
      {
        return ResourceManager.GetString("Hizmetler", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to İletişim.
    /// </summary>
    public static string ILETISIM
    {
      get
      {
        return ResourceManager.GetString("ILETISIM", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to İsim Soyisim.
    /// </summary>
    public static string İsimSoyisim
    {
      get
      {
        return ResourceManager.GetString("İsimSoyisim", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Kalite Politikamız.
    /// </summary>
    public static string KalitePolitikasi
    {
      get
      {
        return ResourceManager.GetString("KalitePolitikasi", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Kişisel Verilerin Korunması Kanunu.
    /// </summary>
    public static string KVKK
    {
      get
      {
        return ResourceManager.GetString("KVKK", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to 2.
    /// </summary>
    public static string LANG_CODE
    {
      get
      {
        return ResourceManager.GetString("LANG_CODE", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to en.
    /// </summary>
    public static string LANG_NAME
    {
      get
      {
        return ResourceManager.GetString("LANG_NAME", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mesajınız.
    /// </summary>
    public static string Message
    {
      get
      {
        return ResourceManager.GetString("Message", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lütfen e-mail adresi giriniz.
    /// </summary>
    public static string MessageEmail
    {
      get
      {
        return ResourceManager.GetString("MessageEmail", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Beklenmeyen bir hata oluştu. Lütfen daha sonra tekrar deneyiniz.
    /// </summary>
    public static string MessageError
    {
      get
      {
        return ResourceManager.GetString("MessageError", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lütfen mesajınızı giriniz.
    /// </summary>
    public static string MessageMessage
    {
      get
      {
        return ResourceManager.GetString("MessageMessage", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lütfen İsim Giriniz.
    /// </summary>
    public static string MessageName
    {
      get
      {
        return ResourceManager.GetString("MessageName", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lütfen konu giriniz.
    /// </summary>
    public static string MessageSubject
    {
      get
      {
        return ResourceManager.GetString("MessageSubject", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mesajınız başarıyla gönderildi..
    /// </summary>
    public static string MessageSuccess
    {
      get
      {
        return ResourceManager.GetString("MessageSuccess", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Mesajınız.
    /// </summary>
    public static string MessageText
    {
      get
      {
        return ResourceManager.GetString("MessageText", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lütfen geçerli bir e-mail adresi giriniz.
    /// </summary>
    public static string MessageValidatedMail
    {
      get
      {
        return ResourceManager.GetString("MessageValidatedMail", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Lütfen geçerli bir isim giriniz.
    /// </summary>
    public static string MessageValidatedNameSurname
    {
      get
      {
        return ResourceManager.GetString("MessageValidatedNameSurname", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Sayfa Bulunamadı.
    /// </summary>
    public static string PageNotFound
    {
      get
      {
        return ResourceManager.GetString("PageNotFound", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Projeler.
    /// </summary>
    public static string Projeler
    {
      get
      {
        return ResourceManager.GetString("Projeler", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Projelerimiz.
    /// </summary>
    public static string Projelerimiz
    {
      get
      {
        return ResourceManager.GetString("Projelerimiz", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to &apos;nu okudum, anladım, kabul ediyorum..
    /// </summary>
    public static string ReadAccept
    {
      get
      {
        return ResourceManager.GetString("ReadAccept", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Anasayfaya Dön.
    /// </summary>
    public static string ReturnHomepage
    {
      get
      {
        return ResourceManager.GetString("ReturnHomepage", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Telefon Numarısı.
    /// </summary>
    public static string Telefon
    {
      get
      {
        return ResourceManager.GetString("Telefon", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tüm hakları saklıdır..
    /// </summary>
    public static string TumHaklar
    {
      get
      {
        return ResourceManager.GetString("TumHaklar", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Tüm Projelerimiz.
    /// </summary>
    public static string TumProjelerimiz
    {
      get
      {
        return ResourceManager.GetString("TumProjelerimiz", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Apps.
    /// </summary>
    public static string Uygulamalar
    {
      get
      {
        return ResourceManager.GetString("Uygulamalar", resourceCulture);
      }
    }
  }
}
